# Configuração do servidor
server.port=${SERVER_PORT:8080}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}
server.forward-headers-strategy=native

# Configuração de compressão do servidor
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024

# Configuração do Ollama
spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL:llama3.2}
spring.ai.ollama.chat.options.temperature=${OLLAMA_TEMPERATURE:0.7}

# Configuração JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Configuração de Autenticação
auth.subject=${AUTH_SUBJECT:myapp}
auth.access-key=${AUTH_ACCESS_KEY:secretkey123}

# Configuração do Swagger/OpenAPI
springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH:/api-docs}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui-custom.html}
springdoc.packages-to-scan=${SPRINGDOC_PACKAGES_TO_SCAN:com.caio.ollama_integration.controller,com.caio.ollama_integration.rest.controller}
springdoc.swagger-ui.tryItOutEnabled=${SPRINGDOC_SWAGGER_UI_TRY_IT_OUT_ENABLED:true}
springdoc.swagger-ui.operationsSorter=${SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER:method}
springdoc.swagger-ui.tagsSorter=${SPRINGDOC_SWAGGER_UI_TAGS_SORTER:alpha}
springdoc.swagger-ui.filter=${SPRINGDOC_SWAGGER_UI_FILTER:true}
springdoc.swagger-ui.persist-authorization=${SPRINGDOC_SWAGGER_UI_PERSIST_AUTHORIZATION:true}

# Logging
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.level.org.apache.catalina=${LOGGING_LEVEL_ORG_APACHE_CATALINA:INFO}
logging.level.org.apache.http=${LOGGING_LEVEL_ORG_APACHE_HTTP:INFO}
logging.level.org.apache.tomcat=${LOGGING_LEVEL_ORG_APACHE_TOMCAT:INFO}
logging.level.org.hibernate=${LOGGING_LEVEL_ORG_HIBERNATE:INFO}
logging.level.org.springframework=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:INFO}

# Configurações do Jackson para serialização e desserialização de datas
spring.jackson.serialization.write-dates-as-timestamps=${SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS:false}
spring.jackson.deserialization.adjust-dates-to-context-time-zone=${SPRING_JACKSON_DESERIALIZATION_ADJUST_DATES_TO_CONTEXT_TIME_ZONE:true}

# Configurações de upload (multipart)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB